services:
  db:
    labels:
      - com.host.description=Postgres data store for the lottery application
    image: postgres:18
    container_name: lottery-db
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    environment:
      POSTGRES_DB: ${LOTTERY_POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${LOTTERY_POSTGRES_PASSWORD}
      # needs to know the migrator creds because the init_users.sh script uses
      # these to create the migrator user
      LOTTERY_MIGRATOR_DB_USER: ${LOTTERY_MIGRATOR_DB_USER}
      LOTTERY_MIGRATOR_DB_PASSWORD: ${LOTTERY_MIGRATOR_DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql
      # Run an init script to create the migration user that db-bootstrap will use
      - ./db/init_users.sh:/docker-entrypoint-initdb.d/init_users.sh

  db-bootstrap:
    labels:
      - com.host.description=Runs the EF migration and seeds any initial data
    build:
      context: .
      dockerfile: src/Lottery.DB.Bootstrap/dockerfile

    depends_on:
      db:
        condition: service_healthy

    environment:
      LOTTERY_POSTGRES_DB: ${LOTTERY_POSTGRES_DB}
      ConnectionStrings__Default: "Host=db;Database=${LOTTERY_POSTGRES_DB};Username=${LOTTERY_MIGRATOR_DB_USER};Password=${LOTTERY_MIGRATOR_DB_PASSWORD}"

      # bootstrap needs to know DB credentials for users that need to be created
      LOTTERY_API_DB_USER: ${LOTTERY_API_DB_USER}
      LOTTERY_API_DB_PASSWORD: ${LOTTERY_API_DB_PASSWORD}
      LOTTERY_RESULTS_DB_USER: ${LOTTERY_RESULTS_DB_USER}
      LOTTERY_RESULTS_DB_PASSWORD: ${LOTTERY_RESULTS_DB_PASSWORD}
      # bootstrap needs to know app credentials the app service accounts
      LOTTERY_SYSTEM_ADMIN_PASSWORD: ${LOTTERY_SYSTEM_ADMIN_PASSWORD}
      LOTTERY_GAME_ADMIN_PASSWORD: ${LOTTERY_GAME_ADMIN_PASSWORD}

  api:
    labels:
      - com.host.description=The API which is consumed by the lottery UI to manage and interact with lottery games

    depends_on:
      db-bootstrap:
        condition: service_completed_successfully

    build:
      context: .
      dockerfile: src/Lottery.Api/dockerfile

    container_name: lottery-api
    restart: unless-stopped

    # API will always run on 8080 in the container,
    # but we can access the API outside the container via LOTTERY_API_PORT env var
    # 8080 is required in the container, as this is what the UI server proxies to
    ports:
      - ${LOTTERY_API_PORT}:8080

    environment:
      LOTTERY_API_PORT: 8080
      EMAIL_API_KEY: ${EMAIL_API_KEY}
      ConnectionStrings__Default: Host=db;Database=${LOTTERY_POSTGRES_DB};Username=${LOTTERY_API_DB_USER};Password=${LOTTERY_API_DB_PASSWORD}

  resulting:
    labels:
      - com.host.description=A background service which periodically checks games to be resulted and results them

    depends_on:
      db-bootstrap:
        condition: service_completed_successfully

    build:
      context: .
      dockerfile: src/Lottery.ResultService/dockerfile

    restart: unless-stopped

    environment:
      ConnectionStrings__Default: Host=db;Database=${LOTTERY_POSTGRES_DB};Username=${LOTTERY_RESULTS_DB_USER};Password=${LOTTERY_RESULTS_DB_PASSWORD}

  ui:
    labels:
      - com.host.description=The UI to manage and interact with lottery games

    depends_on:
      - api

    build:
      context: src/Lottery.UI
      dockerfile: dockerfile

    container_name: lottery-ui
    restart: unless-stopped

    # UI will always be hosted on port 80 in the container,
    # but can be accessed from outside the container on LOTTERY_UI_PORT
    ports:
      - ${LOTTERY_UI_PORT}:80

volumes:
  postgres_data:
