@Lottery.Api_HostAddress = http://localhost:5264

POST {{Lottery.Api_HostAddress}}/account/signIn
Accept: application/json
Content-Type: application/json

{
  "username": "GameAdmin",
  "password": "{{$dotenv GameAdmin_Password}}",
  "staySignedIn": true
}

###

# @name createGame
POST {{Lottery.Api_HostAddress}}/game/
Accept: application/json
Content-Type: application/json

{
    "state":"Enabled",
    "name": "Test Game", 
    "startTime": "2024-03-02T11:43:39.151Z", 
    "drawTime": "2024-03-03T11:43:39.151Z", 
    "numbersRequired": 5,
    "selections": [
        { "selectionNumber": 1 },
        { "selectionNumber": 2 },
        { "selectionNumber": 3 },
        { "selectionNumber": 4 },
        { "selectionNumber": 5 },
        { "selectionNumber": 6 },
        { "selectionNumber": 7 }
    ],
    "prizes": [
      { "position": 1, "numberMatchCount": 5 },
      { "position": 2, "numberMatchCount": 4 },
      { "position": 3, "numberMatchCount": 3 }
    ]
}

### 

@gameId = {{createGame.response.body.$.id}}
# @name createEntry
POST {{Lottery.Api_HostAddress}}/entry
Accept: application/json
Content-Type: application/json

{
  "gameId": "@{{gameId}}"
}