CREATE TABLE IF NOT EXISTS migration_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_migration_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'idt') THEN
        CREATE SCHEMA idt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dbo') THEN
        CREATE SCHEMA dbo;
    END IF;
END $EF$;

CREATE TYPE item_state AS ENUM ('enabled', 'disabled');

CREATE TABLE idt.app_role (
    id uuid NOT NULL,
    display_name character varying(64) NOT NULL,
    description character varying(64) NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_app_role" PRIMARY KEY (id)
);

CREATE TABLE idt.app_user (
    id uuid NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_app_user" PRIMARY KEY (id)
);

CREATE TABLE idt.app_role_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_app_role_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_app_role_claim_app_role_role_id" FOREIGN KEY (role_id) REFERENCES idt.app_role (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_app_user_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_app_user_claim_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_login (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT "PK_app_user_login" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_app_user_login_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT "PK_app_user_role" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_app_user_role_app_role_role_id" FOREIGN KEY (role_id) REFERENCES idt.app_role (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_app_user_role_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_token (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_app_user_token" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_app_user_token_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.entry (
    id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_entry" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.game (
    id uuid NOT NULL,
    start_time timestamp with time zone NOT NULL,
    draw_time timestamp with time zone NOT NULL,
    name character varying(64) NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game" PRIMARY KEY (id),
    CONSTRAINT "FK_game_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.game_prize (
    id uuid NOT NULL,
    game_id uuid NOT NULL,
    position integer NOT NULL,
    number_match_count integer NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game_prize" PRIMARY KEY (id),
    CONSTRAINT "FK_game_prize_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_game_prize_game_game_id" FOREIGN KEY (game_id) REFERENCES dbo.game (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.game_selection (
    id uuid NOT NULL,
    selection_number integer NOT NULL,
    game_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game_selection" PRIMARY KEY (id),
    CONSTRAINT "FK_game_selection_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_game_selection_game_game_id" FOREIGN KEY (game_id) REFERENCES dbo.game (id) ON DELETE RESTRICT
);

CREATE TABLE entry_prize (
    id uuid NOT NULL,
    game_id uuid NOT NULL,
    game_prize_id uuid NOT NULL,
    entry_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_entry_prize" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_prize_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_prize_entry_entry_id" FOREIGN KEY (entry_id) REFERENCES dbo.entry (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_prize_game_game_id" FOREIGN KEY (game_id) REFERENCES dbo.game (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_prize_game_prize_game_prize_id" FOREIGN KEY (game_prize_id) REFERENCES dbo.game_prize (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.entry_selection (
    id uuid NOT NULL,
    entry_id uuid NOT NULL,
    game_selection_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_entry_selection" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_selection_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_selection_entry_entry_id" FOREIGN KEY (entry_id) REFERENCES dbo.entry (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_selection_game_selection_game_selection_id" FOREIGN KEY (game_selection_id) REFERENCES dbo.game_selection (id) ON DELETE RESTRICT
);

CREATE TABLE game_results (
    id uuid NOT NULL,
    game_id uuid NOT NULL,
    selection_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    updated_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game_results" PRIMARY KEY (id),
    CONSTRAINT "FK_game_results_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_game_results_game_game_id" FOREIGN KEY (game_id) REFERENCES dbo.game (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_game_results_game_selection_selection_id" FOREIGN KEY (selection_id) REFERENCES dbo.game_selection (id) ON DELETE RESTRICT
);

INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('404b4bce-c7d7-4499-bbdf-4788387bf335', '02c5a8a4e1b24cc2a44730e4e4a35f7b', 'Permission to create and edit any games', 'Game Admin', 'GameAdmin', 'GAMEADMIN');
INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('9dd4d5c1-0885-4ab4-bd5b-abf4610709f0', '79309286379f43ec8dfe050c8a9fcc34', 'Elevated permissions across the entire system.', 'System Administrator', 'SystemAdministrator', 'SYSTEMADMINISTRATOR');
INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('a38fbbda-b36a-45ae-9eac-582a91a1aeab', 'ef7c467c12c644a1bda3ef1fcf992df0', 'Permission to access the site and play games.', 'Basic User', 'BasicUser', 'BASICUSER');

INSERT INTO idt.app_user (id, access_failed_count, concurrency_stamp, email, email_confirmed, lockout_enabled, lockout_end, normalized_email, normalized_user_name, password_hash, phone_number, phone_number_confirmed, security_stamp, two_factor_enabled, user_name)
VALUES ('119cc8c1-d2c2-4f5a-a49d-70a0ed7d8f0e', 0, '46a7b68fc3634787a476fb289c2eac95', 'SystemAdministrator@Lottery.Game', TRUE, FALSE, NULL, 'SYSTEMADMINISTRATOR@LOTTERY.GAME', 'SYSTEMADMIN', 'AQAAAAIAAYagAAAAEHZFOTCIKzyAydE+0eYMIyjQqK31jvGSjSNPdSLE/KAhTaJDrWX4OfLYMXS5tqmLOg==', NULL, FALSE, '3705829a5e304f26b461de2da2c58b34', FALSE, 'SystemAdmin');
INSERT INTO idt.app_user (id, access_failed_count, concurrency_stamp, email, email_confirmed, lockout_enabled, lockout_end, normalized_email, normalized_user_name, password_hash, phone_number, phone_number_confirmed, security_stamp, two_factor_enabled, user_name)
VALUES ('ffa78a18-194a-4aa0-a220-9fdce45c61d9', 0, '32349b48c83943fe8c8ffc44ed198c83', 'GameAdmin@Lottery.Game', TRUE, FALSE, NULL, 'GAMEADMIN@LOTTERY.GAME', 'GAMEADMIN', 'AQAAAAIAAYagAAAAECdQD2EjPV0stUR6ukVG3TbIAK4aa/T3LjIMInkpRhMEyfc93TB0FyTw6/0WYKWAUw==', NULL, FALSE, '72db710761804a20a3a2411d1d2fdbbd', FALSE, 'GameAdmin');

INSERT INTO idt.app_user_role (role_id, user_id)
VALUES ('9dd4d5c1-0885-4ab4-bd5b-abf4610709f0', '119cc8c1-d2c2-4f5a-a49d-70a0ed7d8f0e');
INSERT INTO idt.app_user_role (role_id, user_id)
VALUES ('404b4bce-c7d7-4499-bbdf-4788387bf335', 'ffa78a18-194a-4aa0-a220-9fdce45c61d9');

CREATE UNIQUE INDEX "RoleNameIndex" ON idt.app_role (normalized_name);

CREATE INDEX "IX_app_role_claim_role_id" ON idt.app_role_claim (role_id);

CREATE INDEX "EmailIndex" ON idt.app_user (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON idt.app_user (normalized_user_name);

CREATE INDEX "IX_app_user_claim_user_id" ON idt.app_user_claim (user_id);

CREATE INDEX "IX_app_user_login_user_id" ON idt.app_user_login (user_id);

CREATE INDEX "IX_app_user_role_role_id" ON idt.app_user_role (role_id);

CREATE INDEX "IX_entry_created_by_id" ON dbo.entry (created_by_id);

CREATE INDEX "IX_entry_prize_created_by_id" ON entry_prize (created_by_id);

CREATE UNIQUE INDEX "IX_entry_prize_entry_id" ON entry_prize (entry_id);

CREATE INDEX "IX_entry_prize_game_id" ON entry_prize (game_id);

CREATE INDEX "IX_entry_prize_game_prize_id" ON entry_prize (game_prize_id);

CREATE INDEX "IX_entry_selection_created_by_id" ON dbo.entry_selection (created_by_id);

CREATE INDEX "IX_entry_selection_entry_id" ON dbo.entry_selection (entry_id);

CREATE INDEX "IX_entry_selection_game_selection_id" ON dbo.entry_selection (game_selection_id);

CREATE INDEX "IX_game_created_by_id" ON dbo.game (created_by_id);

CREATE INDEX "IX_game_prize_created_by_id" ON dbo.game_prize (created_by_id);

CREATE INDEX "IX_game_prize_game_id" ON dbo.game_prize (game_id);

CREATE INDEX "IX_game_results_created_by_id" ON game_results (created_by_id);

CREATE INDEX "IX_game_results_game_id" ON game_results (game_id);

CREATE INDEX "IX_game_results_selection_id" ON game_results (selection_id);

CREATE INDEX "IX_game_selection_created_by_id" ON dbo.game_selection (created_by_id);

CREATE INDEX "IX_game_selection_game_id" ON dbo.game_selection (game_id);

INSERT INTO migration_history ("MigrationId", "ProductVersion")
VALUES ('20240307175811_InitialMigration', '8.0.2');

COMMIT;

