CREATE TABLE IF NOT EXISTS migration_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_migration_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'idt') THEN
        CREATE SCHEMA idt;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dbo') THEN
        CREATE SCHEMA dbo;
    END IF;
END $EF$;

CREATE TYPE item_state AS ENUM ('enabled', 'disabled');

CREATE TABLE idt.app_role (
    id uuid NOT NULL,
    display_name character varying(64) NOT NULL,
    description character varying(64) NOT NULL,
    name character varying(256),
    normalized_name character varying(256),
    concurrency_stamp text,
    CONSTRAINT "PK_app_role" PRIMARY KEY (id)
);

CREATE TABLE idt.app_user (
    id uuid NOT NULL,
    user_name character varying(256),
    normalized_user_name character varying(256),
    email character varying(256),
    normalized_email character varying(256),
    email_confirmed boolean NOT NULL,
    password_hash text,
    security_stamp text,
    concurrency_stamp text,
    phone_number text,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT "PK_app_user" PRIMARY KEY (id)
);

CREATE TABLE idt.app_role_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    role_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_app_role_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_app_role_claim_app_role_role_id" FOREIGN KEY (role_id) REFERENCES idt.app_role (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_claim (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL,
    claim_type text,
    claim_value text,
    CONSTRAINT "PK_app_user_claim" PRIMARY KEY (id),
    CONSTRAINT "FK_app_user_claim_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_login (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text,
    user_id uuid NOT NULL,
    CONSTRAINT "PK_app_user_login" PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT "FK_app_user_login_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_role (
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT "PK_app_user_role" PRIMARY KEY (user_id, role_id),
    CONSTRAINT "FK_app_user_role_app_role_role_id" FOREIGN KEY (role_id) REFERENCES idt.app_role (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_app_user_role_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE idt.app_user_token (
    user_id uuid NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text,
    CONSTRAINT "PK_app_user_token" PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT "FK_app_user_token_app_user_user_id" FOREIGN KEY (user_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.entry (
    id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_entry" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.game (
    id uuid NOT NULL,
    start_time timestamp with time zone NOT NULL,
    draw_time timestamp with time zone NOT NULL,
    name character varying(64) NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game" PRIMARY KEY (id),
    CONSTRAINT "FK_game_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.game_selection (
    id uuid NOT NULL,
    selection_number integer NOT NULL,
    game_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_game_selection" PRIMARY KEY (id),
    CONSTRAINT "FK_game_selection_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_game_selection_game_game_id" FOREIGN KEY (game_id) REFERENCES dbo.game (id) ON DELETE RESTRICT
);

CREATE TABLE dbo.entry_selection (
    id uuid NOT NULL,
    entry_id uuid NOT NULL,
    game_selection_id uuid NOT NULL,
    created_on_utc timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    created_by_id uuid NOT NULL,
    state integer NOT NULL DEFAULT 1,
    state_last_updated timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT "PK_entry_selection" PRIMARY KEY (id),
    CONSTRAINT "FK_entry_selection_app_user_created_by_id" FOREIGN KEY (created_by_id) REFERENCES idt.app_user (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_selection_entry_entry_id" FOREIGN KEY (entry_id) REFERENCES dbo.entry (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_entry_selection_game_selection_game_selection_id" FOREIGN KEY (game_selection_id) REFERENCES dbo.game_selection (id) ON DELETE RESTRICT
);

INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('45ed77a2-36f5-44b5-aba2-21835a3110ef', 'a0162189da75467b8f2bfd9e38f9e632', 'Permission to access the site and play games.', 'Basic User', 'BasicUser', 'BASICUSER');
INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('488c804e-5321-404e-9c8c-c333f79604c1', '05857132a7cb44f3922075263e424ded', 'Permission to create and edit any games', 'Game Admin', 'GameAdmin', 'GAMEADMIN');
INSERT INTO idt.app_role (id, concurrency_stamp, description, display_name, name, normalized_name)
VALUES ('a0738ca5-9f1d-4c34-9829-cd2c389ae31f', '90c473a2b7f94cda8b281a62b6014020', 'Elevated permissions across the entire system.', 'System Administrator', 'SystemAdministrator', 'SYSTEMADMINISTRATOR');

INSERT INTO idt.app_user (id, access_failed_count, concurrency_stamp, email, email_confirmed, lockout_enabled, lockout_end, normalized_email, normalized_user_name, password_hash, phone_number, phone_number_confirmed, security_stamp, two_factor_enabled, user_name)
VALUES ('19f40d93-4d51-4458-9e9c-998568aed063', 0, '43f056d36bc24fc9b559c5440b65ca17', 'SystemAdministrator@Lottery.Game', TRUE, FALSE, NULL, 'SYSTEMADMINISTRATOR@LOTTERY.GAME', 'SYSTEMADMIN', 'AQAAAAIAAYagAAAAEEC+tzoapmfsiLIV7l2aHjFAdFUyOfODeQfgOnrZCmByUYFO/qwokNopTAQGZ84Tmg==', NULL, FALSE, '5e605c9a4aa043059565de7b250133e7', FALSE, 'SystemAdmin');
INSERT INTO idt.app_user (id, access_failed_count, concurrency_stamp, email, email_confirmed, lockout_enabled, lockout_end, normalized_email, normalized_user_name, password_hash, phone_number, phone_number_confirmed, security_stamp, two_factor_enabled, user_name)
VALUES ('26fb4004-f122-48eb-9a0d-6df7cda1107e', 0, 'a1b58288e7a24241adbd535a7cede74f', 'GameAdmin@Lottery.Game', TRUE, FALSE, NULL, 'GAMEADMIN@LOTTERY.GAME', 'GAMEADMIN', 'AQAAAAIAAYagAAAAEFTc5+gREzjqz6PActjgXbzorR9yOkq+c/Fg4e4HjrdhOpfXkJSiPasYQBgMUZPWeQ==', NULL, FALSE, '328a742b02134136aad33c2e63da733f', FALSE, 'GameAdmin');

INSERT INTO idt.app_user_role (role_id, user_id)
VALUES ('a0738ca5-9f1d-4c34-9829-cd2c389ae31f', '19f40d93-4d51-4458-9e9c-998568aed063');
INSERT INTO idt.app_user_role (role_id, user_id)
VALUES ('488c804e-5321-404e-9c8c-c333f79604c1', '26fb4004-f122-48eb-9a0d-6df7cda1107e');

CREATE UNIQUE INDEX "RoleNameIndex" ON idt.app_role (normalized_name);

CREATE INDEX "IX_app_role_claim_role_id" ON idt.app_role_claim (role_id);

CREATE INDEX "EmailIndex" ON idt.app_user (normalized_email);

CREATE UNIQUE INDEX "UserNameIndex" ON idt.app_user (normalized_user_name);

CREATE INDEX "IX_app_user_claim_user_id" ON idt.app_user_claim (user_id);

CREATE INDEX "IX_app_user_login_user_id" ON idt.app_user_login (user_id);

CREATE INDEX "IX_app_user_role_role_id" ON idt.app_user_role (role_id);

CREATE INDEX "IX_entry_created_by_id" ON dbo.entry (created_by_id);

CREATE INDEX "IX_entry_selection_created_by_id" ON dbo.entry_selection (created_by_id);

CREATE INDEX "IX_entry_selection_entry_id" ON dbo.entry_selection (entry_id);

CREATE INDEX "IX_entry_selection_game_selection_id" ON dbo.entry_selection (game_selection_id);

CREATE INDEX "IX_game_created_by_id" ON dbo.game (created_by_id);

CREATE INDEX "IX_game_selection_created_by_id" ON dbo.game_selection (created_by_id);

CREATE INDEX "IX_game_selection_game_id" ON dbo.game_selection (game_id);

INSERT INTO migration_history ("MigrationId", "ProductVersion")
VALUES ('20240302111722_InitialMigration', '8.0.2');

COMMIT;

