// <auto-generated />
using System;
using Lottery.DB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lottery.DB.Migrations
{
    [DbContext(typeof(MaintenanceDBContext))]
    partial class MaintenanceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_type", new[] { "user", "service" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "item_state", new[] { "enabled", "disabled" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GameId");

                    b.ToTable("entry", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.EntryPrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("GamePrizeId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_prize_id");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("EntryId")
                        .IsUnique();

                    b.HasIndex("GamePrizeId", "EntryId")
                        .IsUnique();

                    b.ToTable("entry_prize", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.EntrySelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<Guid>("GameSelectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_selection_id");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GameSelectionId");

                    b.HasIndex("EntryId", "GameSelectionId")
                        .IsUnique();

                    b.ToTable("entry_selection", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DrawTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("draw_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<int>("NumbersRequired")
                        .HasColumnType("integer")
                        .HasColumnName("numbers_required");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("game", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GamePrize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("NumberMatchCount")
                        .HasColumnType("integer")
                        .HasColumnName("number_match_count");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GameId", "NumberMatchCount")
                        .IsUnique();

                    b.HasIndex("GameId", "Position")
                        .IsUnique();

                    b.ToTable("game_prize", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GameResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("SelectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("selection_id");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SelectionId");

                    b.HasIndex("GameId", "SelectionId")
                        .IsUnique();

                    b.ToTable("game_result", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GameSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<int>("SelectionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("selection_number");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("state");

                    b.Property<DateTime>("StateLastUpdatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("state_last_updated_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("GameId", "SelectionNumber")
                        .IsUnique();

                    b.ToTable("game_selection", "dbo");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("app_role", "idt");

                    b.HasData(
                        new
                        {
                            Id = new Guid("19b7d67e-1ad8-4407-b627-d5f56534952f"),
                            ConcurrencyStamp = "ab02ef94ec384cc49049fc2a5c5b3061",
                            Description = "Elevated permissions across the entire system.",
                            DisplayName = "System Administrator",
                            Name = "SystemAdministrator",
                            NormalizedName = "SYSTEMADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("226919e5-1ad7-41d2-b04f-4aaa1a1bb2ea"),
                            ConcurrencyStamp = "3cea94e0ff784364b49c9df292555af0",
                            Description = "Permission to create and edit any games",
                            DisplayName = "Game Admin",
                            Name = "GameAdmin",
                            NormalizedName = "GAMEADMIN"
                        },
                        new
                        {
                            Id = new Guid("5ca47808-83c0-4eab-a034-1a48cefa3c4a"),
                            ConcurrencyStamp = "ed2350457c1b4c18afc9d13c23ed5a05",
                            Description = "Permission to access the site and play games.",
                            DisplayName = "Basic User",
                            Name = "BasicUser",
                            NormalizedName = "BASICUSER"
                        },
                        new
                        {
                            Id = new Guid("db16d273-ae17-4822-bbf8-120cec7e3a58"),
                            ConcurrencyStamp = "cf7a8e8a2eef4e13b6dfeeeed3064cda",
                            Description = "Role to be assumed by user accounts used by backend services.",
                            DisplayName = "Service Account",
                            Name = "ServiceAccount",
                            NormalizedName = "SERVICEACCOUNT"
                        });
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("app_role_claim", "idt");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<int>("AccountType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("account_type");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("app_user", "idt");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5621cc59-6211-42d2-a4e3-e9584c248adb"),
                            AccessFailedCount = 0,
                            AccountType = 0,
                            ConcurrencyStamp = "6cd1f1703ac548e2a9295d2568fdc229",
                            Email = "SystemAdministrator@Lottery.Game",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SYSTEMADMINISTRATOR@LOTTERY.GAME",
                            NormalizedUserName = "SYSTEMADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEDwIZYUsECFbX8jyI6oujyQNsZphVSpLCXTaBoW8ta2Td2yhrkBMUQuLx4R8CoRdfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "421123fe685b4be1a9b63c6d809583e5",
                            TwoFactorEnabled = false,
                            UserName = "SystemAdmin"
                        },
                        new
                        {
                            Id = new Guid("295c6034-e0ff-4c22-a94a-14fb4b6659a8"),
                            AccessFailedCount = 0,
                            AccountType = 0,
                            ConcurrencyStamp = "0c057e3ddbb746aa9fd1ad3f9b98488d",
                            Email = "GameAdmin@Lottery.Game",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAMEADMIN@LOTTERY.GAME",
                            NormalizedUserName = "GAMEADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPkZPfF6vAdFP7EW+fw9L7JDwvGLMYtp2AMuTgnRudV7tBRtVxrBdOAPm2mAOwNtXA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d2761ece200c4ead95f643a5227218a5",
                            TwoFactorEnabled = false,
                            UserName = "GameAdmin"
                        },
                        new
                        {
                            Id = new Guid("a3564302-1a9e-4917-8a48-1a70f211279e"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "ff152f04ba8649f196c20b5f090b7659",
                            Email = "Lottery.Api@Lottery.Game",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LOTTERY.API@LOTTERY.GAME",
                            NormalizedUserName = "LOTTERY.API",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc1b6b3b3982424f8f5e93d05c4eeb44",
                            TwoFactorEnabled = false,
                            UserName = "Lottery.Api"
                        },
                        new
                        {
                            Id = new Guid("aeb0bc13-14d4-4999-82c3-ec4b95a56818"),
                            AccessFailedCount = 0,
                            AccountType = 1,
                            ConcurrencyStamp = "b0851a4bec7c489aaf7a37f311a6a946",
                            Email = "Lottery.ResultService@Lottery.Game",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "LOTTERY.RESULTSERVICE@LOTTERY.GAME",
                            NormalizedUserName = "LOTTERY.RESULTSERVICE",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d440692d809e4e2f921e06722aed9ef3",
                            TwoFactorEnabled = false,
                            UserName = "Lottery.ResultService"
                        });
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_claim", "idt");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("app_user_login", "idt");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("app_user_role", "idt");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("5621cc59-6211-42d2-a4e3-e9584c248adb"),
                            RoleId = new Guid("19b7d67e-1ad8-4407-b627-d5f56534952f")
                        },
                        new
                        {
                            UserId = new Guid("295c6034-e0ff-4c22-a94a-14fb4b6659a8"),
                            RoleId = new Guid("226919e5-1ad7-41d2-b04f-4aaa1a1bb2ea")
                        },
                        new
                        {
                            UserId = new Guid("a3564302-1a9e-4917-8a48-1a70f211279e"),
                            RoleId = new Guid("db16d273-ae17-4822-bbf8-120cec7e3a58")
                        },
                        new
                        {
                            UserId = new Guid("aeb0bc13-14d4-4999-82c3-ec4b95a56818"),
                            RoleId = new Guid("db16d273-ae17-4822-bbf8-120cec7e3a58")
                        });
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("app_user_token", "idt");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Entry", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany("Entries")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Game", "Game")
                        .WithMany("Entries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.EntryPrize", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Entry", "Entry")
                        .WithOne("Prize")
                        .HasForeignKey("Lottery.DB.Entities.Dbo.EntryPrize", "EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.GamePrize", "GamePrize")
                        .WithMany("EntryPrizes")
                        .HasForeignKey("GamePrizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Entry");

                    b.Navigation("GamePrize");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.EntrySelection", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Entry", "Entry")
                        .WithMany("Selections")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.GameSelection", "GameSelection")
                        .WithMany()
                        .HasForeignKey("GameSelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Entry");

                    b.Navigation("GameSelection");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Game", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GamePrize", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Game", "Game")
                        .WithMany("Prizes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GameResult", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.GameSelection", "Selection")
                        .WithMany()
                        .HasForeignKey("SelectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Game");

                    b.Navigation("Selection");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GameSelection", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Dbo.Game", "Game")
                        .WithMany("Selections")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppRoleClaim", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserClaim", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserLogin", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserRole", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUserToken", b =>
                {
                    b.HasOne("Lottery.DB.Entities.Idt.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Entry", b =>
                {
                    b.Navigation("Prize");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.Game", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Prizes");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Dbo.GamePrize", b =>
                {
                    b.Navigation("EntryPrizes");
                });

            modelBuilder.Entity("Lottery.DB.Entities.Idt.AppUser", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
